<a href="https://colab.research.google.com/github/be4oo/Deep_learning_course/blob/main/2dnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr)
print(arr.shape)
print(type(arr))

[[10 20 30 40]
 [50 60 70 80]]
(2, 4)
<class 'numpy.ndarray'>


In [3]:
y = np.array([1,2,3,4,5,6])
print(y[0:3])

[1 2 3]


In [4]:
print(arr[1:2,2:3])

[[70]]


In [5]:
zeroarr = np.zeros((3,3))
print(zeroarr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
onearr = np.ones(((3,3)))
print((onearr))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
constarr = np.full((3,3),7)
print(constarr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [8]:
ident = np.eye(3)
print(ident)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
randarr = np.random.random((3,3))
print(randarr)

[[0.85208126 0.78006978 0.6517654 ]
 [0.20102624 0.45908144 0.16813194]
 [0.20392626 0.28115669 0.81061306]]
